# Generated by Django 4.0.6 on 2022-08-13 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_dead_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='dead_line',
            new_name='datecompleted',
        ),
    ]
